### ISSUE TITLE
2.0.1: `autoapi` documentation not ready for `sphinx` 6.x

### ISSUE THREAD

**Issue by kloczek** [carlos-jenkins/autoapi#11]
Looks like autoapi` documentation needs to be updated for `sphinx` 6.x.
```console
+ /usr/bin/sphinx-build -n -T -b man doc build/sphinx/man
Running Sphinx v6.1.3
making output directory... done

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 279, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 237, in __init__
    self.config.setup(self)
  File "/home/tkloczko/rpmbuild/BUILD/autoapi-2.0.1/doc/conf.py", line 100, in setup
    app.add_stylesheet('styles/custom.css')
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'

Exception occurred:
  File "/home/tkloczko/rpmbuild/BUILD/autoapi-2.0.1/doc/conf.py", line 100, in setup
    app.add_stylesheet('styles/custom.css')
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
The full traceback has been saved in /tmp/sphinx-err-3d8lvvbt.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by kloczek** [comment]
gentle ping .. any update? 🤔
