### ISSUE TITLE
Incapability of handle dict on the `source_suffix`

### ISSUE THREAD

**Issue by jastinsoares** [carlos-jenkins/autoapi#3]
By default `source_suffix` at the **conf.py** is defined like this:

```python
source_suffix = ['.rst']
```
or
```python
source_suffix = ['.rst','.md']
```

But when a user reads the documentation from Sphinx 1.8.0+, it is said that you can define it like:
```python
source_suffix = {
'.rst': 'restructuredtext',
'.txt': 'restructuredtext',
'.md': 'markdown',
}
```

The problem by using dict on the configuration makes you package to crash at the line 161 from the **sphinx.py**:
```python
out_file = join(out_dir, node.name + app.config.source_suffix[0])
```

My suggestions is to identy the type of `app.config.source_suffix` and dynamically acess/handle it based on this information.

**Comment by buhtz** [comment]
I have to add some more detailed informations here. I thought my problem depends on a quite new version of Sphinx I am using with debian unstable.

Please see line 4 of this output as debug information I added myself.

```
$ make html
Sphinx v1.8.1 in Verwendung
Lade pickle Umgebung...erledigt
DEBUG app.config.source_suffix = OrderedDict([('.rst', None)])
/usr/local/lib/python2.7/dist-packages/sphinx/application.py:388: RemovedInSphinx20Warning: app.warning() is now deprecated. Use sphinx.util.logging instead.
  RemovedInSphinx20Warning)
WARNING: Unhandled exception in autoapi module: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/autoapi/sphinx.py", line 48, in wrapper
    func(app)
  File "/usr/local/lib/python2.7/dist-packages/autoapi/sphinx.py", line 162, in builder_inited
    out_file = join(out_dir, node.name + app.config.source_suffix[0])
KeyError: 0

building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: [] 0 added, 1 changed, 0 removed
reading sources... [100%] index                                                                                        
/home/user/share/work/buhtz-sphinx/doc/source/index.rst:9: WARNING: toctree contains reference to nonexisting document u'buhtzsphinx/buhtzsphinx'
looking for now-outdated files... none found
pickling environment... erledigt
checking consistency... erledigt
preparing documents... erledigt
writing output... [100%] index                                                                                         
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... erledigt
dumping search index in English (code: en) ... erledigt
dumping object inventory... erledigt
build abgeschlossen, 2 warnings.

The HTML pages are in build/html.

```

So I think it does not depend on how `source_suffix` is defined. It is always an `OrderedDict`. But I am not aware of since which version of Sphinx this changed.
