### ISSUE TITLE
Incompatibility with Sphinx 2.0

### ISSUE THREAD

**Issue by petrbel** [carlos-jenkins/autoapi#5]
Hi,
I run into a problem after updating to Sphinx 2.0.1. I'm using this command `sphinx-build . build -vvv`. Here I enclose the produced log:

```
# Sphinx version: 2.0.1
# Python version: 3.7.2 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/petrbel/.pyenv/versions/3.7.2/envs/shepherd/lib/python3.7/site-packages/autoapi/sphinx.py", line 48, in wrapper
    func(app)
  File "/home/petrbel/.pyenv/versions/3.7.2/envs/shepherd/lib/python3.7/site-packages/autoapi/sphinx.py", line 161, in builder_inited
    out_file = join(out_dir, node.name + app.config.source_suffix[0])
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/petrbel/.pyenv/versions/3.7.2/envs/shepherd/lib/python3.7/site-packages/sphinx/cmd/build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/petrbel/.pyenv/versions/3.7.2/envs/shepherd/lib/python3.7/site-packages/sphinx/application.py", line 260, in __init__
    self._init_builder()
  File "/home/petrbel/.pyenv/versions/3.7.2/envs/shepherd/lib/python3.7/site-packages/sphinx/application.py", line 321, in _init_builder
    self.emit('builder-inited')
  File "/home/petrbel/.pyenv/versions/3.7.2/envs/shepherd/lib/python3.7/site-packages/sphinx/application.py", line 440, in emit
    return self.events.emit(event, self, *args)
  File "/home/petrbel/.pyenv/versions/3.7.2/envs/shepherd/lib/python3.7/site-packages/sphinx/events.py", line 76, in emit
    results.append(callback(*args))
  File "/home/petrbel/.pyenv/versions/3.7.2/envs/shepherd/lib/python3.7/site-packages/autoapi/sphinx.py", line 50, in wrapper
    app.warn(
AttributeError: 'Sphinx' object has no attribute 'warn'
```

Sphinx 2 probably dropped `warn` (`AttributeError: 'Sphinx' object has no attribute 'warn'`)

**Comment by petrbel** [comment]
Thanks @carlos-jenkins, it works!
